package platform

import (
	"crypto/rand"
	"encoding/hex"
	"strings"
)

// BuildPhoneBookEntry 构造 RAS 电话簿条目（与旧版字段逐项一致）。
func BuildPhoneBookEntry(connName, port, device string) string {
	guid := randomGuid()
	var b strings.Builder
	b.WriteString("[" + connName + "]\n")
	b.WriteString("Encoding=1\n")
	b.WriteString("PBVersion=8\n")
	b.WriteString("Type=5\n")
	b.WriteString("AutoLogon=0\n")
	b.WriteString("UseRasCredentials=0\n")
	b.WriteString("LowDateTime=0\n")
	b.WriteString("HighDateTime=0\n")
	b.WriteString("DialParamsUID=0\n")
	b.WriteString("Guid=" + guid + "\n")
	b.WriteString("VpnStrategy=0\n")
	b.WriteString("ExcludedProtocols=0\n")
	b.WriteString("LcpExtensions=1\n")
	b.WriteString("DataEncryption=8\n")
	b.WriteString("SwCompression=1\n")
	b.WriteString("NegotiateMultilinkAlways=1\n")
	b.WriteString("SkipDoubleDialDialog=0\n")
	b.WriteString("DialMode=0\n")
	b.WriteString("OverridePref=15\n")
	b.WriteString("RedialAttempts=3\n")
	b.WriteString("RedialSeconds=60\n")
	b.WriteString("IdleDisconnectSeconds=0\n")
	b.WriteString("RedialOnLinkFailure=1\n")
	b.WriteString("CallbackMode=0\n")
	b.WriteString("CustomDialDll=\n")
	b.WriteString("CustomDialFunc=\n")
	b.WriteString("CustomRasDialDll=\n")
	b.WriteString("ForceSecureCompartment=0\n")
	b.WriteString("DisableIKENameEkuCheck=0\n")
	b.WriteString("AuthenticateServer=0\n")
	b.WriteString("ShareMsFilePrint=1\n")
	b.WriteString("BindMsNetClient=1\n")
	b.WriteString("SharedPhoneNumbers=0\n")
	b.WriteString("GlobalDeviceSettings=0\n")
	b.WriteString("PrerequisiteEntry=\n")
	b.WriteString("PrerequisitePbk=\n")
	b.WriteString("PreferredPort=" + port + "\n")
	b.WriteString("PreferredDevice=" + device + "\n")
	b.WriteString("PreferredBps=0\n")
	b.WriteString("PreferredHwFlow=0\n")
	b.WriteString("PreferredProtocol=0\n")
	b.WriteString("PreferredCompression=0\n")
	b.WriteString("PreferredSpeaker=0\n")
	b.WriteString("PreferredMdmProtocol=0\n")
	b.WriteString("PreviewUserPw=1\n")
	b.WriteString("PreviewDomain=0\n")
	b.WriteString("PreviewPhoneNumber=0\n")
	b.WriteString("ShowDialingProgress=1\n")
	b.WriteString("ShowMonitorIconInTaskBar=1\n")
	b.WriteString("CustomAuthKey=0\n")
	b.WriteString("AuthRestrictions=552\n")
	b.WriteString("IpPrioritizeRemote=1\n")
	b.WriteString("IpInterfaceMetric=0\n")
	b.WriteString("IpHeaderCompression=0\n")
	b.WriteString("IpAddress=0.0.0.0\n")
	b.WriteString("IpDnsAddress=0.0.0.0\n")
	b.WriteString("IpDns2Address=0.0.0.0\n")
	b.WriteString("IpWinsAddress=0.0.0.0\n")
	b.WriteString("IpWins2Address=0.0.0.0\n")
	b.WriteString("IpAssign=1\n")
	b.WriteString("IpNameAssign=1\n")
	b.WriteString("IpDnsFlags=0\n")
	b.WriteString("IpNBTFlags=0\n")
	b.WriteString("TcpWindowSize=0\n")
	b.WriteString("UseFlags=3\n")
	b.WriteString("IpSecFlags=0\n")
	b.WriteString("IpDnsSuffix=\n")
	b.WriteString("Ipv6Assign=1\n")
	b.WriteString("Ipv6Address=::\n")
	b.WriteString("Ipv6PrefixLength=0\n")
	b.WriteString("Ipv6PrioritizeRemote=1\n")
	b.WriteString("Ipv6InterfaceMetric=0\n")
	b.WriteString("Ipv6NameAssign=1\n")
	b.WriteString("Ipv6DnsAddress=::\n")
	b.WriteString("Ipv6Dns2Address=::\n")
	b.WriteString("Ipv6Prefix=0000000000000000\n")
	b.WriteString("Ipv6InterfaceId=0000000000000000\n")
	b.WriteString("DisableClassBasedDefaultRoute=0\n")
	b.WriteString("DisableMobility=0\n")
	b.WriteString("NetworkOutageTime=0\n")
	b.WriteString("IDI=\n")
	b.WriteString("IDR=\n")
	b.WriteString("ImsConfig=0\n")
	b.WriteString("IdiType=0\n")
	b.WriteString("IdrType=0\n")
	b.WriteString("ProvisionType=0\n")
	b.WriteString("PreSharedKey=\n")
	b.WriteString("CacheCredentials=0\n")
	b.WriteString("NumCustomPolicy=0\n")
	b.WriteString("NumEku=0\n")
	b.WriteString("UseMachineRootCert=0\n")
	b.WriteString("Disable_IKEv2_Fragmentation=0\n")
	b.WriteString("PlumbIKEv2TSAsRoutes=0\n")
	b.WriteString("NumServers=0\n")
	b.WriteString("RouteVersion=1\n")
	b.WriteString("NumRoutes=0\n")
	b.WriteString("NumNrptRules=0\n")
	b.WriteString("AutoTiggerCapable=0\n")
	b.WriteString("NumAppIds=0\n")
	b.WriteString("NumClassicAppIds=0\n")
	b.WriteString("SecurityDescriptor=\n")
	b.WriteString("ApnInfoProviderId=\n")
	b.WriteString("ApnInfoUsername=\n")
	b.WriteString("ApnInfoPassword=\n")
	b.WriteString("ApnInfoAccessPoint=\n")
	b.WriteString("ApnInfoAuthentication=1\n")
	b.WriteString("ApnInfoCompression=0\n")
	b.WriteString("DeviceComplianceEnabled=0\n")
	b.WriteString("DeviceComplianceSsoEnabled=0\n")
	b.WriteString("DeviceComplianceSsoEku=\n")
	b.WriteString("DeviceComplianceSsoIssuer=\n")
	b.WriteString("FlagsSet=0\n")
	b.WriteString("Options=0\n")
	b.WriteString("DisableDefaultDnsSuffixes=0\n")
	b.WriteString("NumTrustedNetworks=0\n")
	b.WriteString("NumDnsSearchSuffixes=0\n")
	b.WriteString("PowershellCreatedProfile=0\n")
	b.WriteString("ProxyFlags=0\n")
	b.WriteString("ProxySettingsModified=0\n")
	b.WriteString("ProvisioningAuthority=\n")
	b.WriteString("AuthTypeOTP=0\n")
	b.WriteString("GREKeyDefined=0\n")
	b.WriteString("NumPerAppTrafficFilters=0\n")
	b.WriteString("AlwaysOnCapable=0\n")
	b.WriteString("DeviceTunnel=0\n")
	b.WriteString("PrivateNetwork=0\n")
	b.WriteString("ManagementApp=\n\n")
	b.WriteString("NETCOMPONENTS=\n")
	b.WriteString("ms_msclient=1\n")
	b.WriteString("ms_server=1\n\n")
	b.WriteString("MEDIA=rastapi\n")
	b.WriteString("Port=" + port + "\n")
	b.WriteString("Device=" + device + "\n\n")
	b.WriteString("DEVICE=PPPoE\n")
	b.WriteString("PhoneNumber=\n")
	b.WriteString("AreaCode=\n")
	b.WriteString("CountryCode=0\n")
	b.WriteString("CountryID=0\n")
	b.WriteString("UseDialingRules=0\n")
	b.WriteString("Comment=\n")
	b.WriteString("FriendlyName=\n")
	b.WriteString("LastSelectedPhone=0\n")
	b.WriteString("PromoteAlternates=0\n")
	b.WriteString("TryNextAlternateOnFail=1\n\n")
	return b.String()
}

func randomGuid() string {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		buf = []byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
	}
	return strings.ToUpper(hex.EncodeToString(buf))
}
