// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CancelUpdateDownload() {
  return window['go']['main']['App']['CancelUpdateDownload']();
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DiagAction(arg1) {
  return window['go']['main']['App']['DiagAction'](arg1);
}

export function DiagClear() {
  return window['go']['main']['App']['DiagClear']();
}

export function DiagListDevices() {
  return window['go']['main']['App']['DiagListDevices']();
}

export function DiagRewritePhonebook() {
  return window['go']['main']['App']['DiagRewritePhonebook']();
}

export function DiagSelectDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiagSelectDevice'](arg1, arg2, arg3);
}

export function Dial(arg1, arg2) {
  return window['go']['main']['App']['Dial'](arg1, arg2);
}

export function DialCurrentAccount() {
  return window['go']['main']['App']['DialCurrentAccount']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function ExitProgram() {
  return window['go']['main']['App']['ExitProgram']();
}

export function ExportAccounts(arg1) {
  return window['go']['main']['App']['ExportAccounts'](arg1);
}

export function ExportHistory() {
  return window['go']['main']['App']['ExportHistory']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetProbeSummary() {
  return window['go']['main']['App']['GetProbeSummary']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportAccounts() {
  return window['go']['main']['App']['ImportAccounts']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsWindowVisible() {
  return window['go']['main']['App']['IsWindowVisible']();
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function SaveAccounts(arg1) {
  return window['go']['main']['App']['SaveAccounts'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function TestConnectivity() {
  return window['go']['main']['App']['TestConnectivity']();
}

export function UpdateBusy() {
  return window['go']['main']['App']['UpdateBusy']();
}
