// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';
import {service} from '../models';

export function Bootstrap():Promise<main.AppState>;

export function CancelUpdateDownload():Promise<void>;

export function CheckUpdate(arg1:boolean):Promise<void>;

export function ClearHistory():Promise<void>;

export function DiagAction(arg1:string):Promise<boolean>;

export function DiagClear():Promise<void>;

export function DiagListDevices():Promise<Array<main.DeviceOption>>;

export function DiagRewritePhonebook():Promise<string>;

export function DiagSelectDevice(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Dial(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DownloadUpdate():Promise<void>;

export function ExitProgram():Promise<void>;

export function ExportAccounts(arg1:boolean):Promise<string>;

export function ExportHistory():Promise<string>;

export function GetAccounts():Promise<Array<main.AccountDTO>>;

export function GetHistory():Promise<Array<model.HistoryRecord>>;

export function GetProbeSummary():Promise<string>;

export function GetStats():Promise<service.StatsSummary>;

export function HideWindow():Promise<void>;

export function ImportAccounts():Promise<number>;

export function InstallUpdate():Promise<void>;

export function IsWindowVisible():Promise<boolean>;

export function OpenReleasePage(arg1:string):Promise<void>;

export function SaveAccounts(arg1:Array<main.AccountDTO>):Promise<void>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<boolean>;

export function ShowWindow():Promise<void>;

export function SwitchAccount(arg1:number):Promise<void>;

export function TestConnectivity():Promise<main.ProbeResult>;

export function UpdateBusy():Promise<boolean>;

export function UpdateHomeFields(arg1:string,arg2:string,arg3:string):Promise<void>;
