// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['UIApp']['Bootstrap']();
}

export function CancelUpdateDownload() {
  return window['go']['main']['UIApp']['CancelUpdateDownload']();
}

export function CheckUpdate(arg1) {
  return window['go']['main']['UIApp']['CheckUpdate'](arg1);
}

export function DiagListDevices() {
  return window['go']['main']['UIApp']['DiagListDevices']();
}

export function DiagSelectDevice(arg1, arg2, arg3) {
  return window['go']['main']['UIApp']['DiagSelectDevice'](arg1, arg2, arg3);
}

export function Dial() {
  return window['go']['main']['UIApp']['Dial']();
}

export function Disconnect() {
  return window['go']['main']['UIApp']['Disconnect']();
}

export function DownloadUpdate() {
  return window['go']['main']['UIApp']['DownloadUpdate']();
}

export function ExitProgram() {
  return window['go']['main']['UIApp']['ExitProgram']();
}

export function GetBroadband() {
  return window['go']['main']['UIApp']['GetBroadband']();
}

export function GetPortalCredential() {
  return window['go']['main']['UIApp']['GetPortalCredential']();
}

export function GetUILang() {
  return window['go']['main']['UIApp']['GetUILang']();
}

export function HideWindow() {
  return window['go']['main']['UIApp']['HideWindow']();
}

export function InstallUpdate() {
  return window['go']['main']['UIApp']['InstallUpdate']();
}

export function IsWindowVisible() {
  return window['go']['main']['UIApp']['IsWindowVisible']();
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['UIApp']['OpenReleasePage'](arg1);
}

export function SaveBroadband(arg1, arg2) {
  return window['go']['main']['UIApp']['SaveBroadband'](arg1, arg2);
}

export function SavePortalCredential(arg1, arg2) {
  return window['go']['main']['UIApp']['SavePortalCredential'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['UIApp']['SaveSettings'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['UIApp']['SetAutoStart'](arg1);
}

export function SetUILang(arg1) {
  return window['go']['main']['UIApp']['SetUILang'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['UIApp']['ShowWindow']();
}

export function TestPortalAuth() {
  return window['go']['main']['UIApp']['TestPortalAuth']();
}

export function UpdateBusy() {
  return window['go']['main']['UIApp']['UpdateBusy']();
}

export function WifiAvailable() {
  return window['go']['main']['UIApp']['WifiAvailable']();
}

export function WifiConnect(arg1, arg2) {
  return window['go']['main']['UIApp']['WifiConnect'](arg1, arg2);
}

export function WifiDisconnect() {
  return window['go']['main']['UIApp']['WifiDisconnect']();
}

export function WifiScan(arg1) {
  return window['go']['main']['UIApp']['WifiScan'](arg1);
}

export function WifiStatus() {
  return window['go']['main']['UIApp']['WifiStatus']();
}
