// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function Bootstrap():Promise<main.AppState>;

export function CancelUpdateDownload():Promise<void>;

export function CheckUpdate(arg1:boolean):Promise<void>;

export function ClearBroadband():Promise<boolean>;

export function DiagListDevices():Promise<Array<main.DeviceOption>>;

export function DiagRun():Promise<boolean>;

export function DiagSelectDevice(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Dial():Promise<boolean>;

export function Disconnect():Promise<boolean>;

export function DownloadUpdate():Promise<void>;

export function EthLinks():Promise<Array<main.EthLinkDTO>>;

export function ExitProgram():Promise<void>;

export function GetBroadband():Promise<main.BroadbandCredentialDTO>;

export function GetIPInfo():Promise<main.IPInfoDTO>;

export function GetPortalCredential():Promise<main.PortalCredentialDTO>;

export function GetUILang():Promise<main.LangPayload>;

export function HideWindow():Promise<void>;

export function InstallUpdate():Promise<void>;

export function IsWindowVisible():Promise<boolean>;

export function OpenReleasePage(arg1:string):Promise<void>;

export function PppStats():Promise<main.PppStatsDTO>;

export function SaveBroadband(arg1:string,arg2:string):Promise<boolean>;

export function SavePortalCredential(arg1:string,arg2:string):Promise<boolean>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<boolean>;

export function SetUILang(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function SiteLatencyCheck(arg1:Array<string>):Promise<Array<main.SiteLatencyDTO>>;

export function TestPortalAuth():Promise<main.PortalTestResult>;

export function UpdateBusy():Promise<boolean>;

export function WifiAvailable():Promise<boolean>;

export function WifiConnect(arg1:string,arg2:string):Promise<boolean>;

export function WifiDisconnect():Promise<boolean>;

export function WifiScan(arg1:boolean):Promise<Array<main.WifiNetworkDTO>>;

export function WifiStatus():Promise<main.WifiStatusDTO>;
