// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['UIApp']['Bootstrap']();
}

export function CancelUpdateDownload() {
  return window['go']['main']['UIApp']['CancelUpdateDownload']();
}

export function CheckUpdate(arg1) {
  return window['go']['main']['UIApp']['CheckUpdate'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['UIApp']['ClearHistory']();
}

export function DiagAction(arg1) {
  return window['go']['main']['UIApp']['DiagAction'](arg1);
}

export function DiagClear() {
  return window['go']['main']['UIApp']['DiagClear']();
}

export function DiagListDevices() {
  return window['go']['main']['UIApp']['DiagListDevices']();
}

export function DiagRewritePhonebook() {
  return window['go']['main']['UIApp']['DiagRewritePhonebook']();
}

export function DiagSelectDevice(arg1, arg2, arg3) {
  return window['go']['main']['UIApp']['DiagSelectDevice'](arg1, arg2, arg3);
}

export function Dial(arg1, arg2) {
  return window['go']['main']['UIApp']['Dial'](arg1, arg2);
}

export function DialCurrentAccount() {
  return window['go']['main']['UIApp']['DialCurrentAccount']();
}

export function Disconnect() {
  return window['go']['main']['UIApp']['Disconnect']();
}

export function DownloadUpdate() {
  return window['go']['main']['UIApp']['DownloadUpdate']();
}

export function ExitProgram() {
  return window['go']['main']['UIApp']['ExitProgram']();
}

export function ExportAccounts(arg1) {
  return window['go']['main']['UIApp']['ExportAccounts'](arg1);
}

export function ExportHistory() {
  return window['go']['main']['UIApp']['ExportHistory']();
}

export function GetAccounts() {
  return window['go']['main']['UIApp']['GetAccounts']();
}

export function GetHistory() {
  return window['go']['main']['UIApp']['GetHistory']();
}

export function GetProbeSummary() {
  return window['go']['main']['UIApp']['GetProbeSummary']();
}

export function GetStats() {
  return window['go']['main']['UIApp']['GetStats']();
}

export function GetUILang() {
  return window['go']['main']['UIApp']['GetUILang']();
}

export function HideWindow() {
  return window['go']['main']['UIApp']['HideWindow']();
}

export function ImportAccounts() {
  return window['go']['main']['UIApp']['ImportAccounts']();
}

export function InstallUpdate() {
  return window['go']['main']['UIApp']['InstallUpdate']();
}

export function IsWindowVisible() {
  return window['go']['main']['UIApp']['IsWindowVisible']();
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['UIApp']['OpenReleasePage'](arg1);
}

export function SaveAccounts(arg1) {
  return window['go']['main']['UIApp']['SaveAccounts'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['UIApp']['SaveSettings'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['UIApp']['SetAutoStart'](arg1);
}

export function SetUILang(arg1) {
  return window['go']['main']['UIApp']['SetUILang'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['UIApp']['ShowWindow']();
}

export function SwitchAccount(arg1) {
  return window['go']['main']['UIApp']['SwitchAccount'](arg1);
}

export function TestConnectivity() {
  return window['go']['main']['UIApp']['TestConnectivity']();
}

export function UpdateBusy() {
  return window['go']['main']['UIApp']['UpdateBusy']();
}
